version: '3.8'

services:
  # in order to run replica set
  # https://blog.tericcabrel.com/mongodb-replica-set-docker-compose/amp/
  mongodb:
    image: mongo
    restart: always
    networks:
      - starter-network
    ports:
      - "27017:27017"
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: admin
    #      MONGO_INITDB_ROOT_PASSWORD: admin
    #      MONGO_INITDB_DATABASE: nest
    volumes:
      - starterdata:/data/db
  redis:
    image: redis
    container_name: started-redis
    restart: unless-stopped
    networks:
      - starter-network
    volumes:
      - starterdata:/data/db
    ports:
      - "6379:6379"
  vault:
    image: vault:1.7.10
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    volumes:
      - starterdata:/data/vault
networks:
  starter-network:
    driver: bridge
volumes:
  starterdata: